apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\"}}}" .Values.secrets.dockerhub.username .Values.secrets.dockerhub.password .Values.secrets.dockerhub.email | b64enc }}

